//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinMemoryListWithEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewID { get; set; }
        public int CustomerID { get; set; }
        public double Hours { get; set; }
        public int ReviewStatusID { get; set; }
        public int UserID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public Nullable<System.DateTimeOffset> DeletedAt { get; set; }
        public Nullable<int> LastTimeEntryId { get; set; }
        public Nullable<bool> IsViewedByRevieweeAfterFinalized { get; set; }
        public Nullable<bool> IsManual { get; set; }
        public Nullable<int> EngagementID { get; set; }
        public Nullable<int> Session { get; set; }
        public Nullable<bool> IsDismissed { get; set; }
        public Nullable<int> CoachUserID { get; set; }
    }
}
